csv_shipper/users/routes.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from markupsafe import escape

from csv_shipper import bcrypt, db_session
from csv_shipper.models import User, db_add
from csv_shipper.users.utils import send_reset_email
from csv_shipper.users.forms import (
    SignUpForm,
    LoginForm,
    RequestResetForm,
    ResetPasswordForm,
)

users = Blueprint("users", __name__)


@users.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("users.dashboard"))
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        print(hashed_password)
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            username=form.username.data,
            pw_hash=hashed_password,
        )
        db_add(user)
        flash(
            f"Account created for {form.username.data}, you are now able to log in!",
            "primary",
        )
        return redirect(url_for("users.login"))
    return render_template("sign_up.html", title="Sign Up", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.username == form.username.data:
            if bcrypt.check_password_hash(user.pw_hash, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get("next")
                flash(f"Welcome {user.username}!", "primary")
                return (
                    redirect(next_page)
                    if next_page
                    else redirect(url_for("users.dashboard"))
                )
        else:
            flash(
                "Login Unsuccessful, please check your email and password and try again."
            )
    return render_template("log_in.html", title="Log In", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    return render_template("dashboard.html", title="CSV_Shipper Dashboard")


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("users.logout"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(f"A password reset email has been sent to {form.email.data}", "info")
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<string:token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("users.logout"))
    user = User.verify_reset_token(token=token)
    if user is None:
        flash("That is an invalid or expired token.", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.pw_hash = hashed_password
        db_session.commit()
        flash(
            f"Password updated for {form.username.data}, you are now able to log in!",
            "primary",
        )
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)


@users.route("/user/<string:username>", methods=["GET"])
def show_user(username):
    user = User.query.filter_by(username=username).first_or_404(
        description=f"There is no data with the username: {escape(username)}"
    )
    return render_template("show_user.html", user=user)

csv_shipper/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}

    <h1>You are logged in to the User Dashboard! Welcome <strong>{{ current_user.username }}</strong>!</h1>

{% endblock %}

csv_shipper/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>CSV-Shipper</title>
    {% endif %}

    <link href="https://fonts.googleapis.com/css2?family=Muli&display=swap" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
            integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css"
          integrity="sha256-qS+snwBgqr+iFVpBB58C9UCxKFhyL03YHpZfdNUhSEw=" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for("static", filename="css/style.css") }}">

</head>

<body>

{% include "navbar.html" %}

{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="notification is-{{ category }}">
                <button class="delete"></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

<script src="{{ url_for("static", filename="js/app.js") }}"></script>

</body>

</html>

csv_shipper/templates/log_in.html
{% extends "layout.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns is-mobile is-centered">
                <div class="column is-half">
                    <form action="" method="POST">
                        <h1 style="margin-bottom: 50px; margin-top: 100px;" class="is-size-1 has-text-centered">Log in
                            to
                            start Shipping!</h1>

                        {{ form.hidden_tag() }}
                        <div class="field-body">
                            <div class="field">
                                {{ form.email.label(class="label is-small") }}

                                {% if form.email.errors %}
                                    {{ form.email(class="input control is-danger") }}
                                    {% for error in form.email.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.email(class="input control") }}
                                {% endif %}
                            </div>

                            <div class="field">
                                {{ form.username.label(class="label is-small") }}

                                {% if form.username.errors %}
                                    {{ form.username(class="input control is-danger") }}
                                    {% for error in form.username.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.username(class="input control") }}
                                {% endif %}
                            </div>
                        </div>

                        <div class="field">
                            {{ form.password.label(class="label is-small") }}

                            {% if form.password.errors %}
                                {{ form.password(class="input control is-danger") }}
                                {% for error in form.password.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            {% else %}
                                {{ form.password(class="input control") }}
                            {% endif %}
                        </div>

                        <div class="field">
                            <div class="control">
                                {{ form.remember(class="checkbox") }}
                                {{ form.remember.label(class="checkbox") }}
                            </div>
                        </div>

                        <div class="field is-grouped">
                            <div class="control">
                                {{ form.login(class="button is-primary") }}
                            </div>
                        </div>

                        <div class="field is-grouped">
                            <p class="help has-text-left has-text-black">
                                Need an account?
                                <a style="margin-left: 2px;" href="{{ url_for('users.signup') }}">
                                    Sign Up Now
                                </a>
                            </p>
                            <a class="help has-text-right" style="margin-left: auto;"
                               href="{{ url_for("users.reset_request") }}">Forgot password?</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

csv_shipper/templates/navbar.html
<nav class="navbar is-link" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
           data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">

        <div class="navbar-start">
            <a class="navbar-item">
                Home
            </a>

            <a class="navbar-item">
                Documentation
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        About
                    </a>
                    <a class="navbar-item">
                        Jobs
                    </a>
                    <a class="navbar-item">
                        Contact
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

        {% if current_user.is_authenticated %}
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary is-small" href="{{ url_for("users.logout") }}">
                            <strong>Logout</strong>
                        </a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary is-small" href="{{ url_for("users.signup") }}">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-info is-small" href="{{ url_for("users.login") }}">
                            Log in
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
</nav>

csv_shipper/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns is-mobile is-centered">
                <div class="column is-half">
                    <form action="" method="POST">
                        <h1 style="margin-bottom: 50px; margin-top: 100px;" class="is-size-1 has-text-centered">Reset
                            Password</h1>

                        {{ form.hidden_tag() }}
                        <div class="field-body">
                            <div class="field">
                                {{ form.email.label(class="label is-small") }}

                                {% if form.email.errors %}
                                    {{ form.email(class="input control is-danger") }}
                                    {% for error in form.email.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.email(class="input control") }}
                                {% endif %}
                            </div>


                            <div class="field is-grouped">
                                <div class="control">
                                    {{ form.login(class="button is-primary") }}
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

csv_shipper/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns is-mobile is-centered">
                <div class="column is-half">
                    <form action="" method="POST">
                        <h1 style="margin-bottom: 50px; margin-top: 100px;" class="is-size-1 has-text-centered">Reset
                            Password</h1>

                        {{ form.hidden_tag() }}
                        <div class="field-body">
                            <div class="field">
                                {{ form.password.label(class="label is-small") }}

                                {% if form.password.errors %}
                                    {{ form.password(class="input control is-danger") }}
                                    {% for error in form.password.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.password(class="input control") }}
                                {% endif %}
                            </div>

                            <div class="field">
                                {{ form.confirm_password.label(class="label is-small") }}

                                {% if form.confirm_password.errors %}
                                    {{ form.confirm_password(class="input control is-danger") }}
                                    {% for error in form.confirm_password.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.confirm_password(class="input control") }}
                                {% endif %}
                            </div>


                            <div class="field is-grouped">
                                <div class="control">
                                    {{ form.login(class="button is-primary") }}
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

csv_shipper/templates/show_user.html
{% extends 'layout.html' %}
{% block content %}

    <div class="container is-centered">
        <h1>Hello {{ user.first_name|e }} {{ user.last_name|e }}</h1>
        <h3>Username: {{ user.username|e }}</h3>
        <h3>Email: {{ user.email|e }}</h3>
        <h3>Account created: {{ user.created_at|e }}</h3>
    </div>

{% endblock %}

csv_shipper/templates/sign_up.html
{% extends "layout.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns is-mobile is-centered">
                <div class="column is-half">
                    <form action="" method="POST">
                        <h1 class="is-size-1 has-text-centered" style="margin-bottom: 30px;">
                            Sign-Up to Ship Today!
                        </h1>

                        {{ form.hidden_tag() }}
                        <div class="field-body">
                            <div class="field">
                                {{ form.first_name.label(class="label is-small") }}

                                {% if form.first_name.errors %}
                                    {{ form.first_name(class="input control is-danger") }}
                                    {% for error in form.first_name.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.first_name(class="input control") }}
                                {% endif %}
                            </div>

                            <div class="field">
                                {{ form.last_name.label(class="label is-small") }}

                                {% if form.last_name.errors %}
                                    {{ form.last_name(class="input control is-danger") }}
                                    {% for error in form.last_name.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.last_name(class="input control") }}
                                {% endif %}
                            </div>
                        </div>


                        <div class="field">
                            {{ form.email.label(class="label is-small") }}

                            {% if form.email.errors %}
                                {{ form.email(class="input control is-danger") }}
                                {% for error in form.email.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            {% else %}
                                {{ form.email(class="input control") }}
                            {% endif %}
                        </div>


                        <div class="field">
                            {{ form.username.label(class="label is-small") }}

                            {% if form.username.errors %}
                                {{ form.username(class="input control is-danger") }}
                                {% for error in form.username.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            {% else %}
                                {{ form.username(class="input control") }}
                            {% endif %}
                        </div>


                        <div class="field-body">
                            <div class="field">
                                {{ form.password.label(class="label is-small") }}

                                {% if form.password.errors %}
                                    {{ form.password(class="input control is-danger") }}
                                    {% for error in form.password.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.password(class="input control") }}
                                {% endif %}
                            </div>

                            <div class="field">
                                {{ form.confirm_password.label(class="label is-small") }}

                                {% if form.confirm_password.errors %}
                                    {{ form.confirm_password(class="input control is-danger") }}
                                    {% for error in form.confirm_password.errors %}
                                        <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                {% else %}
                                    {{ form.confirm_password(class="input control") }}
                                {% endif %}
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <label class="checkbox">
                                    <input type="checkbox">
                                    I agree to the <a href="#">terms and conditions</a>
                                </label>
                            </div>
                        </div>

                        <div class="field is-grouped">
                            <div class="control">
                                {{ form.submit(class="button is-primary") }}
                            </div>
                        </div>
                    </form>
                    <div class="field" style="margin-top: 15px;">
                        <p class="help has-text-left has-text-black">
                            Already have an account?
                            <a href="{{ url_for("users.login") }}">
                                Log In
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}